Add initial roles
oVirt/ovirt-ansible pull request #1
Opened 2017-04-11 10:19 UTC by machacekondra

This patch add initial implementation of initial roles.

2017-04-11 10:19 UTC, machacekondra commented
@mwperina

2017-04-11 11:55 UTC, mwperina requested changes

2017-04-11 11:55 UTC, mwperina commented on examples/library/parted.py
> +#!/usr/bin/python
Not needed now, please remove the file

2017-04-11 11:55 UTC, mwperina commented on examples/openshift.yml
> +---
Not needed now, please remove this file

2017-04-11 11:55 UTC, mwperina commented on examples/openshift_vars.yml
> +---
Not needed now, please remove the file

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_cluster_upgrade.yml
> +---
Not needed now, please remove the file

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_image_template.yml
> +    engine_url: https://ondra.local/ovirt-engine/api
engine_url: https://ovirt-engine.example.com/ovirt-engine/api

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_infra_vars.yml
> +#engine_url: https://ovirt-engine.example.com/ovirt-engine/api
Please use this one and remove ondra.local

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_infra_vars.yml
> +engine_insecure: true
Please use CA instead of insecure access

2017-04-11 11:55 UTC, mwperina commented on README.md
> +[![Build Status](https://travis-ci.org/machacekondra/ovirt-ansible-roles.svg?branch=master)](https://travis-ci.org/machacekondra/ovirt-ansible-roles)
Is this still valid for official oVirt repo?

2017-04-11 11:55 UTC, mwperina commented on README.md
> +[ovirt-storages]: https://github.com/machacekondra/ovirt-ansible-roles/blob/master/roles/ovirt-storages/README.md
Shouldn't above links be replaced with https://github.com/oVirt/ovirt-ansible

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-image-template/meta/main.yml
> +  description: Role to deploy Manage IQ into oVirt.
Please fix

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-image-template/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-image-template/meta/main.yml
> +  min_ansible_version: 2.2
Ansible 2.3

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-image-template/meta/main.yml
> +  galaxy_tags: [manageiq, cloudforms, ovirt, rhv, rhev, virtualization]
Please remove manageiq/cloudforms reference

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_image_template.yml
> +    engine_cafile: /home/omachace/Downloads/ca.pem
engine_cafile: /etc/pki/ovirt-engine/ca.pem

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_image_template.yml
> +    engine_password: 123456
Use vault instead?

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_infra_vars.yml
> +engine_password: 123456
Use vault instead?

2017-04-11 11:55 UTC, mwperina commented on examples/ovirt_infra_vars.yml
> +
Aren't below VMs OpenShift related?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-aaa-jdbc/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-aaa-jdbc/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-aaa-jdbc/meta/main.yml
> +  #  - Any
Do we need above huge comment included?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-clusters/library/ovirt_clusters.py
> +#!/usr/bin/python
Isn't this module part of Ansible 2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-clusters/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-clusters/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-clusters/meta/main.yml
> +  #  - Any
Do we need huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-datacenters/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-datacenters/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-datacenters/meta/main.yml
> +  #  - Any
Do we need that huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-hosts/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-hosts/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-hosts/meta/main.yml
> +  #  - Any
Huge comment?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-infra/README.md
> +[ovirt-storages]: https://github.com/machacekondra/ovirt-ansible-roles/blob/master/roles/ovirt-storages/README.md
Shouldn't above links be replaced with https://github.com/oVirt/ovirt-ansible ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-infra/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-infra/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-infra/meta/main.yml
> +  #  - Any
Do we need the huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-networks/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-networks/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-networks/meta/main.yml
> +  #  - Any
Do we need a huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-permissions/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-permissions/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-permissions/meta/main.yml
> +  #  - Any
Do we need the huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-storages/library/ovirt_storage_connections.py
> +#!/usr/bin/python
Isn't the module part of Ansible 2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-storages/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-storages/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-storages/meta/main.yml
> +  #  - Any
Do we need that huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-vm-infra/meta/main.yml
> +  company: your company (optional)
Please fix above

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-vm-infra/meta/main.yml
> +  license: license (GPLv2, CC-BY, etc)
Apache License 2.0

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-vm-infra/meta/main.yml
> +  #  - Any
Do we need that huge comment above?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-aaa-jdbc/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-clusters/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-datacenters/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-hosts/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-infra/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-networks/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-permissions/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-storages/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-vm-infra/meta/main.yml
> +  min_ansible_version: 1.2
2.3?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-aaa-jdbc/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-clusters/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-datacenters/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-hosts/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-infra/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-networks/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-permissions/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-storages/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 11:55 UTC, mwperina commented on roles/ovirt-vm-infra/meta/main.yml
> +  galaxy_tags: []
ovirt rhv rhev virtualization ?

2017-04-11 12:41 UTC, machacekondra commented on roles/ovirt-clusters/library/ovirt_clusters.py
> +#!/usr/bin/python
Yes, but this is patched with `post_copy` policy.

2017-04-11 12:47 UTC, machacekondra commented on roles/ovirt-storages/library/ovirt_storage_connections.py
> +#!/usr/bin/python
Unfortunatelly , no:

 https://github.com/ansible/ansible/pull/22239

2017-04-13 23:20 UTC, mwperina approved these changes
👍

2017-04-13 23:21 UTC, mwperina commented
@mykaul @mgoldboi

Are you OK with merging this?

2017-04-16 21:52 UTC, mgoldboi approved these changes
few comments, no blockers. Thanks!

2017-04-16 21:52 UTC, mgoldboi commented on examples/ovirt_vm_infra.yml
> +    - passwords.yml
do we plan to include this file template on the examples as well?

2017-04-16 21:52 UTC, mgoldboi commented on examples/ovirt_vm_infra.yml
> +      ssh_key: ssh-rsa AAA...LGx user@fqdn
should the passowrds.yml file includes cloud-init passwords for those vms, or should we list those here, I think those would be probably needed.

2017-04-16 21:52 UTC, mgoldboi commented on examples/ovirt_infra_vars.yml
> +engine_url: https://ovirt-engine.example.com/ovirt-engine/api
should we change the url to include only FQDN? aren't the suffixes always the same (/ovirt-engine/api)?

2017-04-16 21:52 UTC, mgoldboi commented on roles/ovirt-vm-infra/README.md
> +    engine_cafile: /home/omachace/Downloads/ca.pem
should be changed to /etc..?

2017-04-16 21:52 UTC, mgoldboi commented on examples/ovirt_infra_vars.yml
> +   password: 123456
should we store those on the password.yml as well?

2017-04-17 17:58 UTC, mgoldboi commented
@machacekondra can we merge the changes before the webinar tomorrow?

2017-04-17 18:24 UTC, machacekondra commented
Sure, will do.

2017-04-17 18:32 UTC, machacekondra commented on examples/ovirt_vm_infra.yml
> +    - passwords.yml
done

2017-04-17 18:33 UTC, machacekondra commented on roles/ovirt-vm-infra/README.md
> +    engine_cafile: /home/omachace/Downloads/ca.pem
done

2017-04-17 19:45 UTC, machacekondra commented on examples/ovirt_vm_infra.yml
> +      ssh_key: ssh-rsa AAA...LGx user@fqdn
I will change in another PR

2017-04-17 19:45 UTC, machacekondra commented on examples/ovirt_infra_vars.yml
> +engine_url: https://ovirt-engine.example.com/ovirt-engine/api
I will change in another PR

2017-04-17 19:45 UTC, machacekondra commented on examples/ovirt_infra_vars.yml
> +   password: 123456
I will change in another PR, consolidating all passwords

2017-04-17 19:57 UTC, merged