Edited the ovirt-image-template role.
oVirt/ovirt-ansible pull request #15
Opened 2017-07-19 03:55 UTC by bgraveno

Hi @machacekondra,

Can you please review and merge this request?

Kind regards,

2017-07-19 08:40 UTC, mwperina requested changes

2017-07-19 08:40 UTC, mwperina commented on roles/ovirt-image-template/README.md
> +| image_path         | /tmp/ovirt_image_data | Path where QCOW2 image must be downloaded. |
When role is executed, image will be downloaded from qcow_url and stored locally into image_path. So please change the description to: 'Path where QCOW2 image will be downloaded.'

2017-07-19 08:40 UTC, mwperina commented on roles/ovirt-image-template/README.md
> +| template_disk_storage | UNDEF              | Name of the storage domain where the disk must be created. If not specified, the storage domain is selected automatically. |
I think it should be mentioned that this is data storage domain and not export storage domain.

2017-07-20 00:26 UTC, bgraveno commented on roles/ovirt-image-template/README.md
> +| image_path         | /tmp/ovirt_image_data | Path where QCOW2 image must be downloaded. |
Thanks, updated this to, "Path where the QCOW2 image will be downloaded to."

2017-07-20 00:27 UTC, bgraveno commented on roles/ovirt-image-template/README.md
> +| template_disk_storage | UNDEF              | Name of the storage domain where the disk must be created. If not specified, the storage domain is selected automatically. |
Thanks, I've updated this to specifically mention "data storage domain".

2017-07-20 08:19 UTC, machacekondra approved these changes

2017-07-20 08:20 UTC, merged