introduce ovirt-external-provider role
oVirt/ovirt-ansible pull request #20
Opened 2017-07-20 08:18 UTC by tareqalayan

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 14:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-24 07:42 UTC, mwperina reviewed
Why do we need a role that when we only call the module and not using this role inside other roles? Am I missing something or are you planning to introduce using this role inside other roles in upcoming PRs?

2017-07-24 08:50 UTC, tareqalayan commented
@mwperina I was intending to add this role to be part of the ovirt-infra role.

2017-07-24 08:54 UTC, mwperina commented
@tareqalayan So could you please add it to ovirt-infra within this PRs so it's clear why this role is added?

2017-07-24 10:52 UTC, mwperina commented
ci test please

2017-07-31 14:40 UTC, machacekondra requested changes

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/.travis.yml
> +---
please remove this file

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +# TODO
Why todo?

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +The `ovirt-external-providers` role is used set up oVirt external providers like glance.
I would remove glance. Not everybody knows what that is.

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +| type                              | UNDEF               | Type of the external provider. Values can be os_image, network, os_volume and  foreman. |
Can you please format it as follows::

```
Type of the external provider, values can be:
<ul>
<li>os_image</li>
<li>os_volume</li>
...
</ul>
```

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +| auth_url                          | UNDEF               | Keystone authentication URL of the openstack provider. required: os_image, os_volume and network. |
```
Keystone authentication URL of the openstack provider. Required for following external provider types
<ul>
<li>...</li>
...
</ul>
```

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +   data_center_name: mydatacenter
Why the `dc` vars are needed?

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/defaults/main.yml
> +---
can you please remove this file

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/handlers/main.yml
> +---
can you please remove this file

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/tests/inventory
> +localhost
can you please remove this file

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/tests/test.yml
> +---
can you please remove this file

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/vars/main.yml
> +---
can you please remove this file

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +| auth_url                          | UNDEF               | Keystone authentication URL of the openstack provider. required: os_image, os_volume and network. |
I miss the `data center` variable here.

2017-07-31 14:40 UTC, machacekondra commented on roles/ovirt-infra/meta/main.yml
> +  - ovirt-external-providers
Maybe we should call it before ovirt-permission, so maybe someone want to setup permissions for the external provider...

2017-08-02 11:56 UTC, tareqalayan commented on roles/ovirt-external-providers/.travis.yml
> +---
OK

2017-08-02 11:56 UTC, tareqalayan commented on roles/ovirt-external-providers/README.md
> +# TODO
done

2017-08-02 11:57 UTC, tareqalayan commented on roles/ovirt-external-providers/README.md
> +The `ovirt-external-providers` role is used set up oVirt external providers like glance.
done

2017-08-02 12:07 UTC, tareqalayan commented on roles/ovirt-external-providers/README.md
> +   data_center_name: mydatacenter
not needed

2017-08-02 12:08 UTC, tareqalayan commented on roles/ovirt-external-providers/README.md
> +| auth_url                          | UNDEF               | Keystone authentication URL of the openstack provider. required: os_image, os_volume and network. |
not needed

2017-08-02 12:08 UTC, tareqalayan commented on roles/ovirt-external-providers/README.md
> +   data_center_name: mydatacenter
done

2017-08-02 12:11 UTC, tareqalayan commented on roles/ovirt-external-providers/defaults/main.yml
> +---
done

2017-08-02 12:12 UTC, tareqalayan commented on roles/ovirt-external-providers/handlers/main.yml
> +---
done

2017-08-02 12:12 UTC, tareqalayan commented on roles/ovirt-external-providers/tests/inventory
> +localhost
done

2017-08-02 12:12 UTC, tareqalayan commented on roles/ovirt-external-providers/tests/test.yml
> +---
done

2017-08-02 12:12 UTC, tareqalayan commented on roles/ovirt-external-providers/vars/main.yml
> +---
done

2017-08-02 12:13 UTC, tareqalayan commented on roles/ovirt-infra/meta/main.yml
> +  - ovirt-external-providers
done

2017-08-02 12:15 UTC, tareqalayan reviewed
fixed according to comment

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:15 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 14:55 UTC, machacekondra commented on roles/ovirt-external-providers/README.md
> +| auth_url                          | UNDEF               | Keystone authentication URL of the openstack provider. required: os_image, os_volume and network. |
So why do you pass it in?

 - roles/ovirt-external-providers/tasks/main.yml

Either remove it or document it.

2017-08-02 14:56 UTC, machacekondra requested changes
It's improperly formatted, please verify the format of markdown.

2017-08-06 06:48 UTC, machacekondra commented on roles/ovirt-external-providers/tasks/main.yml
> +    auth_url: "{{ item.auth_url }}"
I think most of those paramaters are not mandatory, so we should use `default(omit)`

2017-08-06 06:50 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +This role expects a list called `external_providers`, which contains information about the external provider. To see example of this list please check the role's documentation.
Please change this to:
``
This role accepts a variable called `external_providers`. 
```

It's new documentation format.

2017-08-06 06:51 UTC, machacekondra commented on roles/ovirt-external-providers/tasks/main.yml
> +    state: "{{ item.state }}"
In doc you say the `default` is `present` which isn't here.

2017-08-06 08:44 UTC, tareqalayan commented on roles/ovirt-external-providers/tasks/main.yml
> +    state: "{{ item.state }}"
done

2017-08-06 08:45 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +This role expects a list called `external_providers`, which contains information about the external provider. To see example of this list please check the role's documentation.
done

2017-08-07 07:27 UTC, machacekondra commented on roles/ovirt-external-providers/tasks/main.yml
> +    auth_url: "{{ item.auth_url }}"
Does all providers have mandatory ^those attributes?

2017-08-08 14:45 UTC, tareqalayan commented on roles/ovirt-external-providers/tasks/main.yml
> +    auth_url: "{{ item.auth_url }}"
Yes i need to pass 
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    type: "{{ item.type }}"
    url: "{{ item.url }}"
    username: "{{ item.username  }}"
    password: "{{ item.password  }}"
    tenant: "{{ item.tenant   }}"
    auth_url: "{{ item.auth_url }}"
    data_center: "{{ item.data_center | default(omit) }}"
 
for the ovirt public glance i passed dummy data on those parameters and it added it. 

how to proceed from here?

2017-08-09 09:20 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +This role accepts a list called `external_providers`, which contains information about the external provider. To see example of this list please check the role's documentation.
Can you change to:
```
This role accepts a variable called `external_providers`.
```
As we have in all other roles?

2017-08-09 09:20 UTC, machacekondra approved these changes
Looks good , thanks, one last comment and I will merge

2017-08-09 09:53 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +This role accepts a list called `external_providers`, which contains information about the external provider. To see example of this list please check the role's documentation.
OK

2017-08-09 10:07 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +To see example of this list please check the role's documentation.
I don't see it's changed?

2017-08-09 10:20 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +To see example of this list please check the role's documentation.
ok

2017-08-09 12:17 UTC, merged