introduce ovirt set mac pool role
oVirt/ovirt-ansible pull request #24
Opened 2017-07-20 17:02 UTC by tareqalayan

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-20 17:02 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-24 10:52 UTC, mwperina commented
ci test please

2017-07-31 14:29 UTC, machacekondra requested changes
I think we should also attach the mac pool to DC or cluster, otherwise this role doesn't make much sense I think

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-infra/README.md
> + This role expects a variable called `mac-ranges` and a variable called `mac_pool_allow_duplicates`
Please be consitent with other descriptions:

```
This role accpts a variable called ....
```

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +* [ovirt-set-mac-pools]:
Can you please remove `set` from the name?

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/.travis.yml
> +---
Please remove this file.

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/README.md
> +oVirt Mac pools
oVirt Mac Pools

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +     mac_pool_allow_duplicates: false
In documentation you use different names.

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/README.md
> +   mac_pool_allow_duplicates: false
In doc, there's different names.

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/defaults/main.yml
> +---
please remove this file

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/handlers/main.yml
> +# handlers file for roles/ovirt-set-mac-pools
please remove this file

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/tests/test.yml
> +---
please remove this file

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/tests/inventory
> +localhost
please remove this file

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/vars/main.yml
> +---
please remove this file

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
So this by default always create 'Default' mac pool, why?

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/README.md
> +| allow_duplicates         | UNDEF                 | If (true) allow a MAC address to be used multiple times in a pool.
I think default is false in your role, not by ovirt engine, so UNDEF is not true also

2017-07-31 14:29 UTC, machacekondra commented on roles/ovirt-set-mac-pools/tasks/main.yml
> +      - "{{ mac_ranges }}"
default(omit) would be resonable here

2017-08-02 12:19 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +* [ovirt-set-mac-pools]:
done

2017-08-02 12:21 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> + This role expects a variable called `mac-ranges` and a variable called `mac_pool_allow_duplicates`
done

2017-08-02 12:22 UTC, tareqalayan commented on roles/ovirt-set-mac-pools/.travis.yml
> +---
done

2017-08-02 12:26 UTC, tareqalayan commented on roles/ovirt-set-mac-pools/tasks/main.yml
> +      - "{{ mac_ranges }}"
done

2017-08-02 12:30 UTC, tareqalayan commented on roles/ovirt-set-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
This is the default one comes with the fresh installed ovirt.

2017-08-02 12:31 UTC, tareqalayan commented on roles/ovirt-set-mac-pools/tests/inventory
> +localhost
done

2017-08-02 12:31 UTC, tareqalayan commented on roles/ovirt-set-mac-pools/tests/test.yml
> +---
done

2017-08-02 12:31 UTC, tareqalayan commented on roles/ovirt-set-mac-pools/vars/main.yml
> +---
done

2017-08-02 12:31 UTC, tareqalayan reviewed
done

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 12:32 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-02 14:52 UTC, machacekondra requested changes
Again, we need to attach the mac-pool to cluster or datacenter, otherwise it doesn't make sense.

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +* [ovirt-set-mac-pools]:
Can you please remove set from the name?

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-infra/README.md
> + This role accepts a variable called `mac-ranges` and a variable called `mac_pool_allow_duplicates`
s/mac-ranges/mac_ranges

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-infra/README.md
> + This role accepts a variable called `mac-ranges` and a variable called `mac_pool_allow_duplicates`
What about `mac_name`

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-infra/README.md
> + * [ovirt-set-mac-pools]
Can you please remove set from the name?

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +[ovirt-set-mac-pools]: https://github.com/oVirt/ovirt-ansible/blob/master/roles/ovirt-set-mac-pools/README.md
Can you please remove set from the name?

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-mac-pools/defaults/main.yml
> +---
Can you please remove this file?

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-mac-pools/handlers/main.yml
> +---
Can you please remove this file?

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-mac-pools/README.md
> +    - ovirt-set-mac-pools
Can you please remove set from the name?

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-mac-pools/README.md
> +                                                      Default value is set by oVirt engine to false.                    |
This is improperly formatted, please verify the formatting.

2017-08-02 14:52 UTC, machacekondra commented on roles/ovirt-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
Do we want to always by default create a 'Default' mac pool range? I don't think it's good idea.

2017-08-02 14:55 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +* [ovirt-set-mac-pools]:
done

2017-08-02 14:59 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> + This role accepts a variable called `mac-ranges` and a variable called `mac_pool_allow_duplicates`
done

2017-08-02 15:00 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> + * [ovirt-set-mac-pools]
done

2017-08-02 15:03 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +     mac_pool_allow_duplicates: false
you mean ovirt-mac-pool/README.md ? 
there it is also mac_pool_allow_duplicates

2017-08-02 15:03 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +[ovirt-set-mac-pools]: https://github.com/oVirt/ovirt-ansible/blob/master/roles/ovirt-set-mac-pools/README.md
done

2017-08-02 15:03 UTC, tareqalayan commented on roles/ovirt-mac-pools/README.md
> +                                                      Default value is set by oVirt engine to false.                    |
done

2017-08-02 15:04 UTC, tareqalayan commented on roles/ovirt-mac-pools/README.md
> +    - ovirt-set-mac-pools
done

2017-08-02 15:04 UTC, tareqalayan commented on roles/ovirt-mac-pools/defaults/main.yml
> +---
done

2017-08-02 15:04 UTC, tareqalayan commented on roles/ovirt-mac-pools/handlers/main.yml
> +---
done

2017-08-02 15:05 UTC, tareqalayan commented on roles/ovirt-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
it is the mac_pool found on the engine, i guess this is the one we wwant to set if mac_pool_name was not specified. 

what do u suggest?

2017-08-02 15:24 UTC, machacekondra commented on roles/ovirt-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
in current flow if I understand correctly, if user don't specify anything. the `ovirt-infra` role will try to remove 'ranges' from 'Default' mac-pool, I think it's not what you want, or is it?

2017-08-02 15:25 UTC, machacekondra commented on roles/ovirt-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
No, actually it fails, that `mac_ranges` is not defined ... it shouldn't

2017-08-02 15:25 UTC, machacekondra commented on roles/ovirt-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
Also if possible please rename `mac_ranges` to `mac_pool_ranges` so we are consistent with mac_pool_name and mac_pool_allow_duplicates

2017-08-03 07:44 UTC, tareqalayan commented on roles/ovirt-mac-pools/tasks/main.yml
> +    name: "{{ mac_pool_name | default('Default') }}"
OK.
so mac_pool_ranges and mac_pool_name should be provided by user.

2017-08-06 06:41 UTC, machacekondra commented
Will we need in fugure more Mac pool ranges? If yes, we should have it as a list.

2017-08-06 06:45 UTC, machacekondra commented on roles/ovirt-mac-pools/tasks/main.yml
> +    - mac_pool_name is define
s/define/defined Please verify

2017-08-06 08:28 UTC, tareqalayan commented on roles/ovirt-mac-pools/tasks/main.yml
> +    - mac_pool_name is define
fixed. 
Maybe we will need a list .. i will try to fix it.

2017-08-08 08:47 UTC, tareqalayan reviewed
mac_ranges can be list as well.

2017-08-08 10:44 UTC, machacekondra commented
And what about multiple mac pools?

2017-08-08 14:21 UTC, tareqalayan commented
support list of mac_pools

2017-08-09 07:41 UTC, tareqalayan commented
@machacekondra 
i am looking into http://docs.ansible.com/ansible/latest/ovirt_clusters_module.html and don't see any mac_pool option. 
i think in 4.1 and 4.2 the mac_pool should be attached to cluster level. 
if the name of the mac_pool is Default it will be attached by default to the cluster. This is what we do. 
but i agree we should attach it explicitly to cluster. 
but i cannot find it in documentation.

2017-08-09 08:56 UTC, tareqalayan commented
@machacekondra  i opened issue https://github.com/ansible/ansible/issues/27943 about ovirt_cluster not supporting the mac_pool, can u please assign it to me?
how do you want to procceed with this PR?

2017-08-09 12:21 UTC, machacekondra commented
> mac_pool, can u please assign it to me?

I don't have permissions to do assignments in upstream Ansible.

> how do you want to procceed with this PR?

I think we can merge it and we do additional PR for clusters roles to assign mac pool.

2017-08-09 12:35 UTC, machacekondra commented on roles/ovirt-mac-pools/tasks/main.yml
> +    - "{{ mac_pools }}"
```yaml
with_items:
 - "{{ mac_pools | default([]) }}"
```
and remove `when`

2017-08-09 12:35 UTC, machacekondra commented on roles/ovirt-infra/README.md
> + This role accepts a variable called `mac_pool_ranges`, `mac_pool_allow_duplicates` and `mac_pool_name`.
Now it accept `mac_pools`

2017-08-09 12:35 UTC, machacekondra commented on roles/ovirt-infra/README.md
> +     mac_pool_name: my_mac_pool
Please change to `mac_pools:`

2017-08-09 12:35 UTC, machacekondra commented on roles/ovirt-mac-pools/README.md
> +
Please add here : 
```
The items in `mac_pools` list can contain the following parameters:
```

2017-08-09 13:08 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> + This role accepts a variable called `mac_pool_ranges`, `mac_pool_allow_duplicates` and `mac_pool_name`.
done

2017-08-09 13:10 UTC, tareqalayan commented on roles/ovirt-infra/README.md
> +     mac_pool_name: my_mac_pool
done

2017-08-09 13:12 UTC, tareqalayan commented on roles/ovirt-mac-pools/README.md
> +
done

2017-08-09 13:12 UTC, tareqalayan commented on roles/ovirt-mac-pools/tasks/main.yml
> +    - "{{ mac_pools }}"
done

2017-08-09 13:21 UTC, machacekondra approved these changes
Looks good, one last nitpick. Please fix and I will merge.

2017-08-09 13:21 UTC, machacekondra commented on roles/ovirt-infra/README.md
> + This role accepts a variable called `mac_pools.
missing '`' at the end

2017-08-09 13:31 UTC, machacekondra commented
ci build please

2017-08-09 13:43 UTC, merged