Edited the ovirt-permissions role.
oVirt/ovirt-ansible pull request #26
Opened 2017-07-21 00:48 UTC by bgraveno

Hi @machacekondra,

Could you please review and merge my changes?

Kind regards,

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 00:48 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-21 09:24 UTC, machacekondra commented
ci test please

2017-07-24 00:40 UTC, bgraveno commented
Hi @machacekondra, 

I've fixed that issue.

Thanks,

2017-07-24 07:33 UTC, mwperina requested changes

2017-07-24 07:33 UTC, mwperina commented on roles/ovirt-permissions/README.md
> +| user_name     | UNDEF          | The user to manage the permission. |
Shouldn't it be changed to 'The user to manage the permission for.'?

2017-07-24 07:33 UTC, mwperina commented on roles/ovirt-permissions/README.md
> +| group_name    | UNDEF          | Name of group to manage the permission. |
Shouldn't it be changed to 'The group to manage the permission for.'?

2017-07-24 07:33 UTC, mwperina commented on roles/ovirt-permissions/README.md
> +| object_name   | UNDEF          | Name of the object where the permission should be assigned. |
Again do we want to allow HTML tags inside documentation?

2017-07-31 12:09 UTC, machacekondra commented
@bgraveno Hi, can you please answer Martin's questions, I am unsure what's gramaticaly correct.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-07-31 12:09 UTC, ovirt-infra commented
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

2017-08-09 03:41 UTC, bgraveno commented on roles/ovirt-permissions/README.md
> +| group_name    | UNDEF          | Name of group to manage the permission. |
I'll make this update. I wasn't sure if we meant, "The user to manage the permission.", or "The user to manage the permission for."

2017-08-09 03:45 UTC, bgraveno commented
Made the suggested changes.

2017-08-09 07:59 UTC, merged