Add role for ManageIQ/CloudForms deployment
oVirt/ovirt-ansible pull request #4
Opened 2017-05-18 19:27 UTC by machacekondra

Add role for ManageIQ/CloudForms deployment

2017-05-19 07:30 UTC, machacekondra commented
@mwperina

2017-05-19 12:52 UTC, machacekondra commented
@mgoldboi @oourfali

2017-05-21 11:15 UTC, oourfali reviewed
Also I wonder whether we should also add DWH properties (so that capacity and utilization will be configured as well).
Do we have these details? Shall we ask the user fo fill them in?

2017-05-21 11:15 UTC, oourfali commented on roles/ovirt-manageiq/README.md
> +|  miq_vm_name       | manageiq_euwe     | Define the name of the ManageIQ/CloudForms VM in oVirt/RHV.|
remove the extra space.

2017-05-21 11:15 UTC, oourfali commented on roles/ovirt-manageiq/tasks/main.yml
> +    msg: "The downloaded file is not valid QCOW file."
"a valid"

2017-05-21 11:15 UTC, oourfali commented on roles/ovirt-manageiq/tasks/main.yml
> +  - name: Wait for VM IP
does the image include an ovirt guest agent?

2017-05-22 08:52 UTC, mwperina requested changes

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> +oVirt/RHV ManageIQ/CloudForms deployment
I'd rephrase as "ManageIQ/CloudForms deployment on top of oVirt/RHV"

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> + - miq_qcow_url - Define the URL where the ManageIQ/CloudForms qcow is stored (default: http://releases.manageiq.org/manageiq-ovirt-euwe-1.ova).
Here we have a link to OVA, below you are using link to qcow2, so shouldn't use single term everywhere and just mention in the doc that both OVA or qcow2 formats can be used?

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> +| miq_vm_os          | rhel_7x64         | Define the operating system of the virtual machine |
The default is upstream, should we should use CentOS instead of RHEL

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> +        ovirt_fqdn: ondra.local
ovirt-engine.example.com

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> +        miq_qcow_url: http://releases.manageiq.org/manageiq-ovirt-euwe-3.qc2
Does ManageIQ provide some link to latest release, so we won't need to update this often?

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> +        - machacekondra.ovirt-manageiq
Shouldn't there be only "ovirt.manageiq" or "ovirt-ansible.ovirt-manageiq"?

2017-05-22 08:52 UTC, mwperina commented on roles/ovirt-manageiq/defaults/main.yml
> +miq_vm_os: rhel_7x64
CentOS?

2017-05-22 08:56 UTC, mgoldboi commented
would be great if we can add the option to configure additional providers as well as part of the deployment/ configuration stage.
for the use case this CF engine is managing a different provider than oVirt. Openshift for example can be nice part of this story.

2017-05-22 09:01 UTC, mwperina commented
> would be great if we can add the option to configure additional providers as well as part of the 
> deployment/ configuration stage.
> for the use case this CF engine is managing a different provider than oVirt. Openshift for example can 
> be nice part of this story.

Not sure if this part of this role, isn't a role configuring OpenShift provider in MiQ part of OpenShift roles, so users could reuse it?

2017-05-23 07:02 UTC, machacekondra commented on roles/ovirt-manageiq/tasks/main.yml
> +  - name: Wait for VM IP
The ManageIQ includes them, I didn't try the CloudForms.

2017-05-23 08:41 UTC, machacekondra commented on roles/ovirt-manageiq/README.md
> +| miq_vm_os          | rhel_7x64         | Define the operating system of the virtual machine |
There is no such option.

2017-05-23 08:51 UTC, machacekondra commented on roles/ovirt-manageiq/README.md
> +        miq_qcow_url: http://releases.manageiq.org/manageiq-ovirt-euwe-3.qc2
I didn't find any.

2017-05-23 08:51 UTC, machacekondra commented on roles/ovirt-manageiq/README.md
> +        - machacekondra.ovirt-manageiq
Yes.

2017-05-23 09:04 UTC, machacekondra commented on roles/ovirt-manageiq/README.md
> + - miq_qcow_url - Define the URL where the ManageIQ/CloudForms qcow is stored (default: http://releases.manageiq.org/manageiq-ovirt-euwe-1.ova).
Added the qcow only.

2017-05-23 09:44 UTC, mwperina commented on roles/ovirt-manageiq/README.md
> +| miq_vm_os          | rhel_7x64         | Define the operating system of the virtual machine |
Ahh, so this is oVirt specific, we need to set VM OS to RHEL, even though CentOS is used for ManageIQ VM.

2017-05-30 10:48 UTC, mwperina approved these changes
Looks good to me, thanks!

2017-06-05 14:15 UTC, machacekondra commented
Added Openshift and DWH support.

2017-06-05 14:30 UTC, mykaul commented
Openshift is unrelated to Manage IQ?

2017-06-05 14:35 UTC, machacekondra commented
It's related, you can for example manage Openshift in RHV all via ManageIQ. This was requested by Moran.

2017-06-05 15:21 UTC, mykaul commented
Makes little sense to me.
I see 2-3 roles:
- Install ManageIQ
- Install OpenShift
- Connect the two.

It's not natural to see it in a single role.

2017-06-05 15:23 UTC, oourfali commented
I also remember we agreed to keep openshift out of the scope of this role.
Am I wrong?

2017-06-05 15:38 UTC, machacekondra commented
It's optional. It's just one API call, so no problem to remove it.

Yes, that could be separated to those roles, I think better it would be if this role just would deploy ManageIQ, register RHV and then the user can use some ManageIQ modules( if any ) and register other providers in post_tasks.

I will split it.

2017-06-12 08:37 UTC, mwperina requested changes
Let's remove Openshift part from this role, it's should be of a different role. Other than that I think it's ready to merge

2017-06-19 09:05 UTC, mwperina approved these changes
👍

2017-06-20 12:30 UTC, merged